# Generated by Django 6.0.1 on 2026-03-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("miniinsta", "0003_comment_follow_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="image_file",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
